# Week 02 Assignment glucose level data


Missing data occurs commonly in many data applications. Especially wearable sensor devices encounter measurement errors resulting in missing data. Although pandas can handle missing data, for instance, to exclude missing data in the descriptive analysis, we might decide to reshape our data to improve quality. We might consider excluding certain rows, columns, or decide to impute our data if we take an argumentative approach. This week we will work with sensor data of a semester 01 project. The data is timeseries related but a lot of sensor errors occurred. First, we inspect the quality data. Then we will work with imputation, interpolation, and smoothing techniques to overcome this issue of the error readings. Finaly we plot the data. Visualization is a method to translate data into information. As a data scientist you should be able to choose an appropiate visualizations. 


Keywords: data loading, data inspection, data exploration, data cleaning, impute data, missing data, timeseries, pandas, visualization, interactive plots, overflow/underflow error

More to read
- https://fennaf.gitbook.io/bfvm22prog1/
- https://towardsdatascience.com/how-to-analyze-blood-glucose-data-with-python-data-science-packages-4f160f9564be


More about pandas and bokeh programming
- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.interpolate.html
- https://rubberduckdebugging.com/
- https://docs.bokeh.org/en/latest/docs/gallery.html


Learning objectives

- Further practice numpy / pandas
- Read, inspect, clean, and impute JSON data. Handle missing data
- Apply different interpolation/smoothing techniques
- Recognize overflow/underflow error
- Perform visual and statistical analysis for time series data
- Maintain development environment 
- Apply coding standards and FAIR principles


Note: you can bring your own sensor data, but for the practical you need some missing data points. 

By the end of this week the student can:

- load a json dataset 
- typecast the Pandas DataFrame to appropiate data types
- inspect the dataset for quality and metadata information
- add a column with interpolated data in Pandas DataFrame
- perform visual analysis

please add your own topics you want to learn here: https://padlet.com/ffeenstra1/69vbvy0l8t32rq55


The assignment consists of 6 parts:

- [part 1: load the data](#0)
     - [Exercise 1.1](#ex-11)
- [part 2: prepare for inspection](#1)
     - [Exercise 2.1](#ex-21)
- [part 3: inspect the data](#2)
     - [Exercise 3.1](#ex-31)
- [part 4: interpolate the data](#3)
     - [Exercise 4.1](#ex-41)
- [part 5: visualize the data](#4)
     - [Exercise 5.1](#ex-51)
- [part 6: Challenge](#5)
     - [Exercise 6.1](#ex-61)

Part 1 and 5 are mandatory, part 6 is optional (bonus)
Mind you that you cannot copy code without referencing the code. If you copy code you need to be able to explain your code verbally and you will not get the full score.

<a name='0'></a>
## Part 1: Load the data

Instructions: Load the json datafile `glucose.json` into a pandas dataframe. Check your dataframe with a `.head()` to compare with the expected outcome. 

Preferably we read the data not with a hard coded data path but using a config file. See https://fennaf.gitbook.io/bfvm22prog1/data-processing/configuration-files/yaml

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>
<ul><li>json.load() method reads a file, pd.read_json converts it to a Pandas DataFrame</li>
    <li>when loading into a Pandas DataFrame use records orientation </li>
</ul>
</details>

<a name='ex-11'></a>
### Code your solution

In [250]:
import json
file = open('glucose.json')
data = json.load(file)

import pandas as pd
df_data = pd.read_json(data)
df_data.head(60)

              ID              time  recordtype glucose
0   2.845000e+03  2019-04-25 00:08           1     109
1   2.850000e+03  2019-04-25 00:50           1
2   2.877000e+03  2019-04-25 07:02           1     123
3   2.881000e+03  2019-04-25 07:34           1     158
4   2.886000e+03  2019-04-25 08:19           1
5   2.899000e+03  2019-04-25 11:01           1     139
6   2.909000e+03  2019-04-25 13:14           1     151
7   2.916000e+03  2019-04-25 14:17           1     129
8   2.922000e+03  2019-04-25 14:45           1     161
9   2.925000e+03  2019-04-25 14:55           1     184
10  2.927000e+03  2019-04-25 14:59           1     178
11  2.929000e+03  2019-04-25 15:00           1     178
12  2.932000e+03  2019-04-25 15:11           1     121
13  2.935000e+03  2019-04-25 15:18           1     111
14  2.937000e+03  2019-04-25 15:22           1     106
15  2.940000e+03  2019-04-25 15:37           1      91
16  2.942000e+03  2019-04-25 15:38           1      97
17  2.944000e+03  2019-04-25 15:44           1     106
18  2.947000e+03  2019-04-25 15:47           1     106
19  2.949000e+03  2019-04-25 15:51           1      97
20  2.951000e+03  2019-04-25 15:55           1      86
21  2.954000e+03  2019-04-25 16:14           1     114
22  2.957000e+03  2019-04-25 16:26           1     129
23  2.960000e+03  2019-04-25 16:35           1     118
24  2.969000e+03  2019-04-25 16:53           1     118
25  2.971000e+03  2019-04-25 17:01           1     115
26  2.974000e+03  2019-04-25 17:11           1     105
27  2.976000e+03  2019-04-25 17:14           1     109
28  2.979000e+03  2019-04-25 17:19           1     107
29  2.981000e+03  2019-04-25 17:21           1     111
30  2.983000e+03  2019-04-25 17:23           1     120
31  2.985000e+03  2019-04-25 17:26           1     137
32  2.987000e+03  2019-04-25 17:30           1     134
33  2.990000e+03  2019-04-25 17:33           1     129
34  2.992000e+03  2019-04-25 17:34           1     125
35  2.994000e+03  2019-04-25 17:40           1     122
36  2.996000e+03  2019-04-25 17:42           1     124
37  2.999000e+03  2019-04-25 17:49           1     127
38  3.001000e+03  2019-04-25 17:53           1     121
39  3.003000e+03  2019-04-25 17:57           1     123
40  3.005000e+03  2019-04-25 18:01           1     122
41  3.008000e+03  2019-04-25 18:04           1     124
42  3.010000e+03  2019-04-25 18:09           1     126
43  3.012000e+03  2019-04-25 18:13           1     128
44  3.026000e+03  2019-04-25 18:53           1     110
45  3.029000e+03  2019-04-25 19:09           1     128
46  3.031000e+03  2019-04-25 19:15           1     116
47  3.034000e+03  2019-04-25 19:29           1     106
48  3.043000e+03  2019-04-25 21:12           1     151
49  3.047000e+03  2019-04-25 21:42           1     126
50  3.050000e+03  2019-04-25 22:02           1     130
51  3.055000e+03  2019-04-25 22:37           1     114
52  3.058000e+03  2019-04-25 22:51           1     106
53  3.062000e+03  2019-04-25 23:31           1     111
54  1.614305e+19  2019-04-25 00:14           0    None
55  1.614305e+19  2019-04-25 00:29           0    None
56  1.614305e+19  2019-04-25 00:44           0    None
57  1.614305e+19  2019-04-25 00:59           0    None
58  1.614305e+19  2019-04-25 01:14           0    None
59  1.614305e+19  2019-04-25 01:29           0    None

#### Expected outcome:

       ID              time  recordtype glucose
0  2845.0  2019-04-25 00:08           1     109
1  2850.0  2019-04-25 00:50           1        
2  2877.0  2019-04-25 07:02           1     123
3  2881.0  2019-04-25 07:34           1     158
4  2886.0  2019-04-25 08:19           1

<a name='1'></a>
## Part 2: Prepare the data

Check the datatypes of your dataframe. The `glucose` field should be an integer, the `time` field should have a datetime format. If the datatypes are different you should typecast them to the right format.
Make sure that your dataset is sorted by the time column


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>
<ul><li>use astype() method or pandas.DataFrame.to_datetime() for instance</li>
    <li>make sure that the empty spaces are filled with NaN. Use errors='coerce'</li>
    <li>set_index(), sort_index() and reset_index() are helpful to sort on index</li>
</ul>
</details>

<a name='ex-21'></a>
### Code your solution

In [251]:
import numpy as np
df_data.replace(r'\s+', np.nan, regex=True)
df_data['glucose'] = pd.to_numeric(df_data['glucose'], errors='coerce')
df_data['ID'] = df_data['ID'].astype(int)
df_data['time'] = pd.to_datetime(df_data['time'])
df_data.sort_values(by='time',ascending=False)
df_data.dtypes

ID                     int64
time          datetime64[ns]
recordtype             int64
glucose              float64
dtype: object

#### Expected outcome:

ID                     int64
time          datetime64[ns]
recordtype             int64
glucose              float64
dtype: object

<a name='2'></a>
## Part 3: Inspect the data

Now that we prepared the data we are going to inspect the data to get more familiar with the data. You can answer the questions below but feel free to explore the data further by plotting and or statistics, group by overviews and so on. 

To be answered at least:
- what is the quantity of the data (observations and features)
- what is the percentage missing data for glucose?
- is there a specific pattern for glucose value and recordtype?
- what is the time range?

Code the solutions to your answers. Create meaningful overviews or statistics

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>
<ul><li>In the week 01 assignment some functions were explained to inspect missing values</li>
    <li>In the week 01 assignment some functions were explained to groupby value</li>
</ul>
</details>

<a name='ex-31'></a>
### Code your solution

In [252]:
observations = len([df_data['ID']==df_data['ID']])
print(f'There are: {observations} observations')
features = df_data.shape
print(f'The features are: {features}')

percentage_missing_values = df_data.isnull().sum() / len(df_data)
print(percentage_missing_values)

df_data.groupby('ID')['time']
# df_data = df_data[df_data.groupby(['ID'])['time'] == df_data.ID]
max_data = df_data['time'].max()
min_data = df_data['time'].min()
print(f'The time range is {min_data} tot {max_data}')



df_data.drop(df_data.index[54:136],inplace=True)
df_data.head(-1)

There are: 1 observations
The features are: (136, 4)
ID            0.000000
time          0.000000
recordtype    0.000000
glucose       0.617647
dtype: float64
The time range is 2019-04-25 00:08:00 tot 2019-04-25 23:48:00

      ID                time  recordtype  glucose
0   2845 2019-04-25 00:08:00           1    109.0
1   2850 2019-04-25 00:50:00           1      NaN
2   2877 2019-04-25 07:02:00           1    123.0
3   2881 2019-04-25 07:34:00           1    158.0
4   2886 2019-04-25 08:19:00           1      NaN
5   2899 2019-04-25 11:01:00           1    139.0
6   2909 2019-04-25 13:14:00           1    151.0
7   2916 2019-04-25 14:17:00           1    129.0
8   2922 2019-04-25 14:45:00           1    161.0
9   2925 2019-04-25 14:55:00           1    184.0
10  2927 2019-04-25 14:59:00           1    178.0
11  2929 2019-04-25 15:00:00           1    178.0
12  2932 2019-04-25 15:11:00           1    121.0
13  2935 2019-04-25 15:18:00           1    111.0
14  2937 2019-04-25 15:22:00           1    106.0
15  2940 2019-04-25 15:37:00           1     91.0
16  2942 2019-04-25 15:38:00           1     97.0
17  2944 2019-04-25 15:44:00           1    106.0
18  2947 2019-04-25 15:47:00           1    106.0
19  2949 2019-04-25 15:51:00           1     97.0
20  2951 2019-04-25 15:55:00           1     86.0
21  2954 2019-04-25 16:14:00           1    114.0
22  2957 2019-04-25 16:26:00           1    129.0
23  2960 2019-04-25 16:35:00           1    118.0
24  2969 2019-04-25 16:53:00           1    118.0
25  2971 2019-04-25 17:01:00           1    115.0
26  2974 2019-04-25 17:11:00           1    105.0
27  2976 2019-04-25 17:14:00           1    109.0
28  2979 2019-04-25 17:19:00           1    107.0
29  2981 2019-04-25 17:21:00           1    111.0
30  2983 2019-04-25 17:23:00           1    120.0
31  2985 2019-04-25 17:26:00           1    137.0
32  2987 2019-04-25 17:30:00           1    134.0
33  2990 2019-04-25 17:33:00           1    129.0
34  2992 2019-04-25 17:34:00           1    125.0
35  2994 2019-04-25 17:40:00           1    122.0
36  2996 2019-04-25 17:42:00           1    124.0
37  2999 2019-04-25 17:49:00           1    127.0
38  3001 2019-04-25 17:53:00           1    121.0
39  3003 2019-04-25 17:57:00           1    123.0
40  3005 2019-04-25 18:01:00           1    122.0
41  3008 2019-04-25 18:04:00           1    124.0
42  3010 2019-04-25 18:09:00           1    126.0
43  3012 2019-04-25 18:13:00           1    128.0
44  3026 2019-04-25 18:53:00           1    110.0
45  3029 2019-04-25 19:09:00           1    128.0
46  3031 2019-04-25 19:15:00           1    116.0
47  3034 2019-04-25 19:29:00           1    106.0
48  3043 2019-04-25 21:12:00           1    151.0
49  3047 2019-04-25 21:42:00           1    126.0
50  3050 2019-04-25 22:02:00           1    130.0
51  3055 2019-04-25 22:37:00           1    114.0
52  3058 2019-04-25 22:51:00           1    106.0

#### Expected outcome percentage missing data
0.6176470588235294

<a name='3'></a>
## Part 4: Interpolate the data

A lot of data is missing. Use interpolation to fill the missing values. Create a new column with the interpolated data. Take an argumentative approach. Select an interpolation method that suits the nature of the data and explain your choice. Mind you that the expected outcome of the interpolation values can differ from the example below

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>
<ul><li>use Pandas.DataFrame.interpolate() method</li>
</ul>
</details>

<a name='ex-41'></a>
### Code your solution

In [253]:

interpolated = df_data['glucose'].interpolate()
df_data.assign(interpolated=interpolated)
df_data['interpolated'] = interpolated
df_data.head(60)

      ID                time  recordtype  glucose  interpolated
0   2845 2019-04-25 00:08:00           1    109.0         109.0
1   2850 2019-04-25 00:50:00           1      NaN         116.0
2   2877 2019-04-25 07:02:00           1    123.0         123.0
3   2881 2019-04-25 07:34:00           1    158.0         158.0
4   2886 2019-04-25 08:19:00           1      NaN         148.5
5   2899 2019-04-25 11:01:00           1    139.0         139.0
6   2909 2019-04-25 13:14:00           1    151.0         151.0
7   2916 2019-04-25 14:17:00           1    129.0         129.0
8   2922 2019-04-25 14:45:00           1    161.0         161.0
9   2925 2019-04-25 14:55:00           1    184.0         184.0
10  2927 2019-04-25 14:59:00           1    178.0         178.0
11  2929 2019-04-25 15:00:00           1    178.0         178.0
12  2932 2019-04-25 15:11:00           1    121.0         121.0
13  2935 2019-04-25 15:18:00           1    111.0         111.0
14  2937 2019-04-25 15:22:00           1    106.0         106.0
15  2940 2019-04-25 15:37:00           1     91.0          91.0
16  2942 2019-04-25 15:38:00           1     97.0          97.0
17  2944 2019-04-25 15:44:00           1    106.0         106.0
18  2947 2019-04-25 15:47:00           1    106.0         106.0
19  2949 2019-04-25 15:51:00           1     97.0          97.0
20  2951 2019-04-25 15:55:00           1     86.0          86.0
21  2954 2019-04-25 16:14:00           1    114.0         114.0
22  2957 2019-04-25 16:26:00           1    129.0         129.0
23  2960 2019-04-25 16:35:00           1    118.0         118.0
24  2969 2019-04-25 16:53:00           1    118.0         118.0
25  2971 2019-04-25 17:01:00           1    115.0         115.0
26  2974 2019-04-25 17:11:00           1    105.0         105.0
27  2976 2019-04-25 17:14:00           1    109.0         109.0
28  2979 2019-04-25 17:19:00           1    107.0         107.0
29  2981 2019-04-25 17:21:00           1    111.0         111.0
30  2983 2019-04-25 17:23:00           1    120.0         120.0
31  2985 2019-04-25 17:26:00           1    137.0         137.0
32  2987 2019-04-25 17:30:00           1    134.0         134.0
33  2990 2019-04-25 17:33:00           1    129.0         129.0
34  2992 2019-04-25 17:34:00           1    125.0         125.0
35  2994 2019-04-25 17:40:00           1    122.0         122.0
36  2996 2019-04-25 17:42:00           1    124.0         124.0
37  2999 2019-04-25 17:49:00           1    127.0         127.0
38  3001 2019-04-25 17:53:00           1    121.0         121.0
39  3003 2019-04-25 17:57:00           1    123.0         123.0
40  3005 2019-04-25 18:01:00           1    122.0         122.0
41  3008 2019-04-25 18:04:00           1    124.0         124.0
42  3010 2019-04-25 18:09:00           1    126.0         126.0
43  3012 2019-04-25 18:13:00           1    128.0         128.0
44  3026 2019-04-25 18:53:00           1    110.0         110.0
45  3029 2019-04-25 19:09:00           1    128.0         128.0
46  3031 2019-04-25 19:15:00           1    116.0         116.0
47  3034 2019-04-25 19:29:00           1    106.0         106.0
48  3043 2019-04-25 21:12:00           1    151.0         151.0
49  3047 2019-04-25 21:42:00           1    126.0         126.0
50  3050 2019-04-25 22:02:00           1    130.0         130.0
51  3055 2019-04-25 22:37:00           1    114.0         114.0
52  3058 2019-04-25 22:51:00           1    106.0         106.0
53  3062 2019-04-25 23:31:00           1    111.0         111.0

#### Example outcome

                 time                   ID  recordtype  glucose  interpolated
0 2019-04-25 00:08:00                 2845           1    109.0    109.000000
1 2019-04-25 00:14:00 -9223372036854775808           0      NaN    109.466667
2 2019-04-25 00:29:00 -9223372036854775808           0      NaN    109.933333
3 2019-04-25 00:44:00 -9223372036854775808           0      NaN    110.400000
4 2019-04-25 00:50:00                 2850           1      NaN    110.866667

<a name='4'></a>
## Part 5: Plot the data

Create a plot with the original data and the interpolated data. Consider what the best representation is for visualisation of actual values and modelled/imputed values. Provide argumentation for the plot of choice. 

Mind you, there are several types of plots. The most used are: 
- Compare values->	Bar, boxplot, violin plot, scatter, line. 
- Show composition-> Stacked bar, pie, mosaic, area, burtin.
- Show distribution-> 	Histogram, density, qqplot, bubble. 
- Analyzing trend-> Line, bar, dual axis 
- Relations-> Scatter, heatmap


### Code your solution

In [254]:
from bokeh.io import output_notebook
from bokeh.plotting import figure, show
from bokeh.layouts import gridplot
from bokeh.io import output_notebook
from bokeh.plotting import ColumnDataSource
output_notebook()

In [255]:
x_data = df_data['time']
y_data_origin = df_data['glucose']
y_data_inter = df_data['interpolated']
print(y_data_inter)

p = figure(x_axis_type='datetime',title='Visualisation of origin and interpolated data')
p.circle(x_data,y_data_origin,size=8,color='red',legend_label='origin')
p.circle(x_data,y_data_inter,size=6,color='blue',legend_label='interpolated')
p.line(x_data,y_data_origin, color='red')
p.line(x_data,y_data_inter, color='blue')

show(p)

0     109.0
1     116.0
2     123.0
3     158.0
4     148.5
5     139.0
6     151.0
7     129.0
8     161.0
9     184.0
10    178.0
11    178.0
12    121.0
13    111.0
14    106.0
15     91.0
16     97.0
17    106.0
18    106.0
19     97.0
20     86.0
21    114.0
22    129.0
23    118.0
24    118.0
25    115.0
26    105.0
27    109.0
28    107.0
29    111.0
30    120.0
31    137.0
32    134.0
33    129.0
34    125.0
35    122.0
36    124.0
37    127.0
38    121.0
39    123.0
40    122.0
41    124.0
42    126.0
43    128.0
44    110.0
45    128.0
46    116.0
47    106.0
48    151.0
49    126.0
50    130.0
51    114.0
52    106.0
53    111.0
Name: interpolated, dtype: float64

<a name='6'></a>
## Part 6: Challenge

It might even be interesting to introduce a widget in which you can select different methods to interpolate.
1. Can you improve the interpolation by choosing an other method?
2. Can you add an rolling mean line? 
2. Can you improve the plot by making it interactive?

<a name='ex-61'></a>
### Code your solution

In [256]:
#CODE YOUR SOLUTION HERE